baseURL: https://wheretofeedtheducksingothenburg.com/

languageCode: en
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

enableRobotsTXT: true

params:
  contact:
    email: duck@wheretofeedtheducksingothenburg.com
  subtitle: Where to feed the ducks in Gothenburg

title: Where to feed the ducks in Gothenburg
description: There is a map with places where you can feed the ducks in Gothenburg.

theme: "wtftdig"
paginate: 20

frontmatter:
  date:
    - ":filename"
    - ":default"

permalinks:
  posts: ":year/:month/:title/"

params:

  mainSections:
    - posts

  og_image: https://wheretofeedtheducksingothenburg.com/preview512sq.png

  announcementSections:
    - tournaments
    - alerts

  social:
    - name: github
      icon: github
      url: https://github.com/wheretofeedtheducksingothenburg

    - name: twitter
      icon: twitter
      url: https://x.com/whrtfddksngtbrg

languages:
  en:
    disabled: false
    contentDir: content/en
    languageCode: en
    languageDirection: ltr
    languageName: English
    title: Where to feed the ducks in Gothenburg
    weight: 1
    params:
      subtitle: knowledge base
      description: There is a map with places where you can feed the ducks in Gothenburg. We've gathered locations with ducks in Gothenburg.

  ru:
    disabled: false
    languageCode: ru
    languageDirection: ltr
    languageName: Russian
    title: Где кормить уток в Гётеборге
    weight: 3
    params:
      subtitle: Знания
      description: Карта с местами для кормления уток в Гётеборге. Мы собрали самые лучшие места, где найти уток в Гётеборге.

  sr:
    disabled: false
    languageCode: sr
    languageDirection: ltr
    languageName: Serbian
    title: Gde hraniti patke u Geteborgu
    weight: 5
    params:
      subtitle: Znanje
      description: Postoji mapa sa mestima gde možete hraniti patke u Geteborgu. Sakuplili smo lokacije sa patkama u Geteborgu.
